import Healthy from '@/components/Healthy'
import Hero from '@/components/Hero'
import Head from 'next/head'
//import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>GYM-BARAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Healthy/>
      
    </>
  )
}
